### PR TITLE
FOX: New URL Service

### PR DESCRIPTION
**Pull request by meriko**
See comment in PlayVideo routine

### CODE REVIEW

**Comment by meriko** [comment]
There is also a new channel for this, feel free to add to Channel Directory:
https://github.com/meriko/FOX.bundle

**Comment by sander1** [comment]
Cool!! I'll add the channel to the channel dir later today.
Thanks!

**Comment by meriko** [comment]
Great! :)

**Comment by meriko** [comment]
Just a note:
I added the service locally, so that must be removed from the FOX.bundle

**Pull request merged**
